### PR TITLE
Add Asus Tinerboard support

### PR DESCRIPTION
**Pull request by karthikpoduval**
Add support for Asus Tinkerboard.

### CODE REVIEW

**Comment by cbrake** [comment]
thanks for the contribution @karthikpoduval  -- I started a build here just for fun -- parsing went through with no problems.

Which board does this `tinker-board` machine target?

https://tinker-board.asus.com/series.html

**Comment by cbrake** [comment]
builds:

```
[cbrake@ceres yoe-distro]$ ls build/tmp/deploy/images/tinker-board/yoe-simple-image*
build/tmp/deploy/images/tinker-board/yoe-simple-image.env                                          build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board.ext4
build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board-20210308151628.rootfs.ext4      build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board.ext4.gz
build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board-20210308151628.rootfs.ext4.gz   build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board.manifest
build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board-20210308151628.rootfs.manifest  build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board.tar.xz
build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board-20210308151628.rootfs.tar.xz    build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board.testdata.json
build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board-20210308151628.rootfs.wic       build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board.wic
build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board-20210308151628.rootfs.wic.bmap  build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board.wic.bmap
build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board-20210308151628.rootfs.wic.xz    build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board.wic.xz
build/tmp/deploy/images/tinker-board/yoe-simple-image-tinker-board-20210308151628.testdata.json
```

**Comment by kraj** [comment]
looks good to me. We should fork meta-rockchip into yoedistro github and use that eventually. but for now its ok to merge.

**Comment by kraj** [comment]
hmmm we also have https://github.com/rockchip-linux/meta-rockchip wierd relationship between these two layers.

**Comment by karthikpoduval** [comment]
> thanks for the contribution @karthikpoduval -- I started a build here just for fun -- parsing went through with no problems.
> 
> Which board does this `tinker-board` machine target?
> 
> https://tinker-board.asus.com/series.html

Its the first tinker board
https://tinker-board.asus.com/product/tinker-board.html

**Comment by karthikpoduval** [comment]
> hmmm we also have https://github.com/rockchip-linux/meta-rockchip wierd relationship between these two layers.

I used the one found in OE layer Index 
https://layers.openembedded.org/layerindex/branch/master/layer/meta-rockchip/

**Pull request merged**
