### PR TITLE
imx8mn_var_som updates

### PR DESCRIPTION
**Pull request by cbrake**

### CODE REVIEW

**Comment by cbrake** [comment]
getting the following error bulding imx-boot:

image

**Comment by cbrake** [comment]
so variscite overrides `do_compile` in their bbappend but does not set `UBOOT_DTB_NAME_EXTRA`

**Comment by cbrake** [comment]
methinks the meta-freescale imx-boot recipe is somewhat out of control ...

**Comment by cbrake** [comment]
Boots, but this start-up system is failing:

```
[**    ] A start job is running for Variscit…IFI setup service (25s / no limit)
[***   ] A start job is running for Variscit…IFI setup service (30s / no limit)
```

**Comment by kraj** [comment]
That looks like Wi-Fi service is failing like we are seeing on other imx8 variscite SOMS as well

**Comment by cbrake** [comment]
Also an image error:

```
NOTE: Installing the following packages: htop kernel-devicetree kernel-image liberation-fonts networkmanager opkg os-release packagegroup-base-ipv6 packagegroup-base-wifi packagegroup-base-zeroconf packagegroup-core-boot packagegroup-core-ssh-openssh packagegroup-core-weston packagegroup-distro-base packagegroup-machine-base psplash qtvirtualkeyboard run-postinsts simpleiot weston-xwayland wireguard-tools yoe-kiosk-browser
NOTE: /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/opkg.conf -t /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/temp/ipktemp/ -o /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends eudev-hwdb --add-ignore-recommends libmodule-build-perl --add-ignore-recommends udev-hwdb install htop kernel-devicetree kernel-image liberation-fonts networkmanager opkg os-release packagegroup-base-ipv6 packagegroup-base-wifi packagegroup-base-zeroconf packagegroup-core-boot packagegroup-core-ssh-openssh packagegroup-core-weston packagegroup-distro-base packagegroup-machine-base psplash qtvirtualkeyboard run-postinsts simpleiot weston-xwayland wireguard-tools yoe-kiosk-browser
ERROR: Unable to install packages. Command '/scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/opkg.conf -t /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/temp/ipktemp/ -o /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends eudev-hwdb --add-ignore-recommends libmodule-build-perl --add-ignore-recommends udev-hwdb install htop kernel-devicetree kernel-image liberation-fonts networkmanager opkg os-release packagegroup-base-ipv6 packagegroup-base-wifi packagegroup-base-zeroconf packagegroup-core-boot packagegroup-core-ssh-openssh packagegroup-core-weston packagegroup-distro-base packagegroup-machine-base psplash qtvirtualkeyboard run-postinsts simpleiot weston-xwayland wireguard-tools yoe-kiosk-browser' returned 4:
 * Solver encountered 4 problem(s):
 * Problem 1/4:
 *   - package weston-xwayland-11.0.3.imx-r0.0.cortexa53-crypto-mx8mn requires wayland >= 1.22.0, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides libc6 >= 2.39+git0+312e159626 needed by wayland-1.22.0.imx-r0.0.cortexa53-crypto-mx8mn
 * 
 * Solution 1:
 *   - do not ask to install a package providing weston-xwayland

 * Problem 2/4:
 *   - package packagegroup-core-weston-1.0-r0.0.all requires wayland-utils, but none of the providers can be installed
 *   - package wayland-utils-1.2.0-r0.0.cortexa53-crypto-mx8mn requires wayland >= 1.22.0, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides libc6 >= 2.39+git0+312e159626 needed by wayland-1.22.0.imx-r0.0.cortexa53-crypto-mx8mn
 * 
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-core-weston

 * Problem 3/4:
 *   - package yoe-kiosk-browser-1.0.0+git0+610be9b29f-r0.0.cortexa53-crypto requires qtwayland, but none of the providers can be installed
 *   - package qtwayland-6.7.1-r0.0.cortexa53-crypto requires wayland >= 1.22.0, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides libc6 >= 2.39+git0+312e159626 needed by wayland-1.22.0.imx-r0.0.cortexa53-crypto-mx8mn
 * 
 * Solution 1:
 *   - do not ask to install a package providing yoe-kiosk-browser

 * Problem 4/4:
 *   - package qtbase-6.7.1-r0.0.cortexa53-crypto-mx8mn requires libegl-imx >= 6.4.11.p2.2-aarch64, but none of the providers can be installed
 *   - package qtvirtualkeyboard-6.7.1-r0.0.cortexa53-crypto requires qtbase >= 6.7.1, but none of the providers can be installed
 *   - package libegl-imx-1:6.4.11.p2.2-aarch64-r0.0.cortexa53-crypto-mx8mn requires wayland >= 1.22.0, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides libc6 >= 2.39+git0+312e159626 needed by wayland-1.22.0.imx-r0.0.cortexa53-crypto-mx8mn
 * 
 * Solution 1:
 *   - do not ask to install a package providing qtvirtualkeyboard

Disfavor package: udev-hwdb
```
This is with `YOE_PROFILE="yoe-glibc-systemd-wayland"`

Trying eglfs ...

**Comment by cbrake** [comment]
with `YOE_PROFILE = "yoe-glibc-systemd-eglfs"`, getting:

```
NOTE: Installing the following packages: htop kernel-devicetree kernel-image liberation-fonts networkmanager opkg os-release packagegroup-base-ipv6 packagegroup-base-wifi packagegroup-base-zeroconf packagegroup-core-boot packagegroup-core-ssh-openssh packagegroup-distro-base packagegroup-machine-base psplash qtvirtualkeyboard run-postinsts simpleiot wireguard-tools yoe-kiosk-browser
NOTE: /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/opkg.conf -t /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/temp/ipktemp/ -o /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends eudev-hwdb --add-ignore-recommends libmodule-build-perl --add-ignore-recommends udev-hwdb install htop kernel-devicetree kernel-image liberation-fonts networkmanager opkg os-release packagegroup-base-ipv6 packagegroup-base-wifi packagegroup-base-zeroconf packagegroup-core-boot packagegroup-core-ssh-openssh packagegroup-distro-base packagegroup-machine-base psplash qtvirtualkeyboard run-postinsts simpleiot wireguard-tools yoe-kiosk-browser
ERROR: Unable to install packages. Command '/scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/opkg.conf -t /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/temp/ipktemp/ -o /scratch4/yoe/yoe-distro/build/tmp/work/imx8mn_var_som-yoe-linux/yoe-kiosk-image/1.0/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends eudev-hwdb --add-ignore-recommends libmodule-build-perl --add-ignore-recommends udev-hwdb install htop kernel-devicetree kernel-image liberation-fonts networkmanager opkg os-release packagegroup-base-ipv6 packagegroup-base-wifi packagegroup-base-zeroconf packagegroup-core-boot packagegroup-core-ssh-openssh packagegroup-distro-base packagegroup-machine-base psplash qtvirtualkeyboard run-postinsts simpleiot wireguard-tools yoe-kiosk-browser' returned 3:
 * Solver encountered 3 problem(s):
 * Problem 1/3:
 *   - package qtbase-6.7.1-r0.0.cortexa53-crypto-mx8mn requires libegl-imx >= 6.4.11.p2.2-aarch64, but none of the providers can be installed
 *   - package qtvirtualkeyboard-6.7.1-r0.0.cortexa53-crypto requires qtbase >= 6.7.1, but none of the providers can be installed
 *   - package libegl-imx-1:6.4.11.p2.2-aarch64-r0.0.cortexa53-crypto-mx8mn requires wayland >= 1.22.0, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides libc6 >= 2.39+git0+312e159626 needed by wayland-1.22.0.imx-r0.0.cortexa53-crypto-mx8mn
 * 
 * Solution 1:
 *   - do not ask to install a package providing qtvirtualkeyboard

 * Problem 2/3:
 *   - package qtbase-6.7.1-r0.0.cortexa53-crypto-mx8mn requires libegl-imx >= 6.4.11.p2.2-aarch64, but none of the providers can be installed
 *   - package yoe-kiosk-browser-1.0.0+git0+c4550fd947-r0.0.cortexa53-crypto requires qtbase >= 6.7.1, but none of the providers can be installed
 *   - package libegl-imx-1:6.4.11.p2.2-aarch64-r0.0.cortexa53-crypto-mx8mn requires wayland >= 1.22.0, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides libc6 >= 2.39+git0+312e159626 needed by wayland-1.22.0.imx-r0.0.cortexa53-crypto-mx8mn
 * 
 * Solution 1:
 *   - do not ask to install a package providing yoe-kiosk-browser

 * Problem 3/3:
 *   - package packagegroup-tools-bluetooth-1.0-r0.0.all requires bluez5-testtools, but none of the providers can be installed
 *   - package packagegroup-machine-base-1.0-r0.0.imx8mn_var_som requires packagegroup-tools-bluetooth, but none of the providers can be installed
 *   - package bluez5-testtools-5.72-r0.0.cortexa53-crypto requires python3-pygobject, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides python3-pycairo needed by python3-pygobject-3.46.0-r0.0.cortexa53-crypto-mx8mn
 * 
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-machine-base

Disfavor package: udev-hwdb
```

**Comment by cbrake** [comment]
`rpi4-64` builds fine. Looking into the `libegl-imx` dependencies a bit more ...

**Comment by cbrake** [comment]
booted the rpi4 image -- comes up beautifully with new kiosk-browser loading screen, etc. The rootfs does not include wayland, so maybe something wrong with libegl-imx dependencies ...

smells like something is stale in build ...

**Comment by cbrake** [comment]
`var-som-mx8` does the same thing, so seems to be common. I'm going to try clean build just to make sure I don't have something stale in sstate.

**Comment by cbrake** [comment]
clean build built with no errors :-)  Guess its time to clean sstate and start fresh ...

**Comment by cbrake** [comment]
@kraj this is ready for review

**Review by kraj — APPROVED** [review]
lgtm

**Pull request merged**
