### PR TITLE
2021.01 Release

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by cbrake** [comment]
@kraj are you concerned about the following message, or do I have something set up wrong here?

```
WARNING: preferred version arm-8.3 of gcc-cross-aarch64 not available (for item virtual/aarch64-yoe-linux-musl-gcc)            
WARNING: versions of gcc-cross-aarch64 available: 10.2.0 arm-10.2 arm-9.2                                             
WARNING: preferred version arm-8.3 of libgcc not available (for item libgcc)                                                   
WARNING: versions of libgcc available: 10.2.0 arm-10.2 arm-9.2                                                                 
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item virtual/aarch64-yoe-linux-musl-compilerlibs)         
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2                                                            
WARNING: preferred version arm-8.3 of nativesdk-gcc-runtime not available (for item virtual/nativesdk-x86_64-yoesdk-linux-compilerlibs)
WARNING: versions of nativesdk-gcc-runtime available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-crosssdk-x86_64-yoesdk-linux not available (for item virtual/x86_64-yoesdk-linux-gcc-crosssdk)
WARNING: versions of gcc-crosssdk-x86_64-yoesdk-linux available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item libatomic)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2                     
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item libstdc++-dev)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2         
WARNING: preferred version arm-8.3 of libgcc not available (for item libgcc)
WARNING: versions of libgcc available: 10.2.0 arm-10.2 arm-9.2                                                                 
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item libatomic-dev)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2             
WARNING: preferred version arm-8.3 of libgcc not available (for item libgcc-dev)
WARNING: versions of libgcc available: 10.2.0 arm-10.2 arm-9.2                                                                 
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item libstdc++)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2                                                 
```

**Comment by kraj** [comment]
@cbrake it seems latest verification build does not show these issues. So we should be ok now.

**Comment by cbrake** [comment]
I'm still seeing the following with odroid-c4 build -- seems to build fine, so don't want to block release if its no big deal.

```
NOTE: Resolving any missing task queue dependencies                     
WARNING: preferred version arm-8.3 of gcc-cross-aarch64 not available (for item virtual/aarch64-yoe-linux-gcc)
WARNING: versions of gcc-cross-aarch64 available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of libgcc not available (for item libgcc)                                                                                   
WARNING: versions of libgcc available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item virtual/aarch64-yoe-linux-compilerlibs)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-crosssdk-x86_64-yoesdk-linux not available (for item virtual/x86_64-yoesdk-linux-gcc-crosssdk)
WARNING: versions of gcc-crosssdk-x86_64-yoesdk-linux available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of nativesdk-gcc-runtime not available (for item virtual/nativesdk-x86_64-yoesdk-linux-compilerlibs)
WARNING: versions of nativesdk-gcc-runtime available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item libstdc++-dev)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of libgcc not available (for item libgcc)
WARNING: versions of libgcc available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item libatomic)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item libatomic-dev)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of libgcc not available (for item libgcc-dev)
WARNING: versions of libgcc available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-runtime not available (for item libstdc++)
WARNING: versions of gcc-runtime available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of gcc-cross-canadian-aarch64 not available (for item gcc-cross-canadian-aarch64)
WARNING: versions of gcc-cross-canadian-aarch64 available: 10.2.0 arm-10.2 arm-9.2
WARNING: preferred version arm-8.3 of nativesdk-libgcc not available (for item nativesdk-libgcc)
WARNING: versions of nativesdk-libgcc available: 10.2.0 arm-10.2 arm-9.2
```

**Comment by kraj** [comment]
I can reproduce it for `MACHINE=odroid-c4-hardkernel` but works ok for `MACHINE=raspberrypi4-64`

**Comment by kraj** [comment]
hmmm meta-odroid introduced this https://github.com/akuster/meta-odroid/commit/146114a458ef915fc98d9dffbdd397abc7a02558
I wonder why @akuster might shed some light.

**Comment by kraj** [comment]
I opened a pull for meta-odroid here https://github.com/akuster/meta-odroid/pull/71 once merged this should be good.

**Pull request merged**
