### PR TITLE
site.conf.example: use YOE_PROFILE instead of DISTRO

### PR DESCRIPTION
**Pull request by shr-project**
* as changed in meta-yoe:
  https://github.com/YoeDistro/meta-yoe/commit/e065ebe40802bba0cd7ea9c1241dfa2d8ff5940d

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
Hi Martin, can you rebase  upload the pull ? if not I can cherry-pick just the change to site.conf.example
oe-core bump conflicted with another megr

**Comment by cbrake** [comment]
there was a merge conflict in sources/openembedded-core -- the hash does not exist.

I removed the openemembedded-core update and merged the  conf/site.conf.sample changes -- do we need to updated openembedded-core as well?

**Comment by shr-project** [comment]
Sorry not sure how that oe-core bump got into the PR in first place, I was planing to send just the site.conf.sample change.

Thanks for sorting it out.

**Comment by shr-project** [comment]
Ah, I had the bison-3.5.1 upgrade cherry-picked there to fix the build, which I've completely forgot about.

**Comment by kraj** [comment]
Thanks Cliff, all is set now.

**Pull request merged**
