### PR TITLE
update layers

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by cbrake** [comment]
so you must need different tags for different archs in docker? IE, docker can't figure out what image to pull automatically based on arch? Looking at the Ubuntu images, it looks like it can have different archs for a single tag:

image

I wonder if we could do something similar?

**Comment by kraj** [comment]
yes I wanted same thing. I explored it a little bit, one issue is that our dockerfile is not same for x86_64 and arm64 since we have to install some 32bit packages and I also looked into `docker buildx` option but it seems it needed docker desktop.

**Comment by cbrake** [comment]
Could we build the images with different dockerfiles (different branches in Git), but then push them to the same tag?

**Comment by kraj** [comment]
Yeah if there is a way to have two dockerfiles in this repo than it might work

**Comment by kraj** [comment]
> Yeah if there is a way to have two dockerfiles in this repo than it might work
@cbrake 
for this release I have taken out the container piece out. We can get arm64 container builds going in next release. Let me know if it looks ok for now.

**Comment by cbrake** [comment]
sounds good!

**Pull request merged**
